### PR TITLE
address_history_info(): limit history to last 10 transactions.

### PR DESCRIPTION
**Pull request by XaviP**
Limit address history to last 10 transactions in address_history_info(). Protection for very large address histories. Maybe it could be improved with a pager?

### CODE REVIEW

**Comment by bhaugen** [comment]
We can paginate easily in OCP/NRP, if that makes any difference to this commit.

**Comment by XaviP** [comment]
@bhaugen how the params have to be? Something like address_history_info(address, page, number_items)? page begins with zero?

**Comment by bhaugen** [comment]
> how the params have to be? Something like address_history_info(address, page, number_items)? page begins with zero?

You don't need to deal with them. We got methods in Django. Example:
http://nrp.sensorica.co/accounting/contributionhistory/6/
(scroll to bottom, I think it's 20 events per page)

**Comment by fosterlynn** [comment]
@XaviP is there a performance issue to bring back a lot of addresses on your side?

**Comment by XaviP** [comment]
I think so. Each call to address_history_info() makes a first call to server for getting the whole list of tx_hashes of the history. Then, for each tx_hash, another call to the server for getting info of that transaction. So can be performance issues in very large histories.
If we make pagination, the first call is needed, but only the tx_hashes of the page that we need to show.

**Comment by bhaugen** [comment]
I'm ok with 10 tx for now.

**Pull request merged**
